import { expect, test } from "@playwright/test";
import { createIsolatedBalanceFixture, loginIsolatedBalanceUser } from "./isolated-balance-fixture";
import { loadClanStatsPage } from "../src/lib/clan/stats/load-clan-stats";

async function ok<T>(query: PromiseLike<{ data: T; error: unknown }>): Promise<NonNullable<T>> {
  const { data, error } = await query;
  expect(error, JSON.stringify(error)).toBeNull();
  return data as NonNullable<T>;
}

test("stats: period-wide filters, wheel, tooltip, record tab and staff qualification boundary", async ({ page }) => {
  test.setTimeout(150_000);
  const f = await createIsolatedBalanceFixture(3);
  try {
    const rows = await ok(f.service.from("matches").insert(Array.from({ length: 10 }, (_, i) => ({ clan_id: f.clanId, game_id: f.gameId, match_type: "intra" as const, status: "finished" as const, played_at: i === 0 ? "2025-07-01T10:00:00Z" : "2025-08-02T10:00:00Z", map_label: i === 0 ? "부산" : "네팔", created_by: f.users[0].id }))).select("id, map_label"));
    await ok(f.service.from("match_players").insert(rows.flatMap((row) => [{ match_id: row.id, user_id: f.users[0].id, team: 1 }, ...(row.map_label === "부산" ? [{ match_id: row.id, user_id: f.users[1].id, team: 2 }] : [])])));
    await ok(f.service.from("match_results").insert(rows.map((row) => ({ match_id: row.id, winner_team: 1 }))));
    const [leader, member] = await Promise.all([f.memberClient(0), f.memberClient(1)]);
    const [staffModel, memberModel] = await Promise.all([loadClanStatsPage(leader, f.users[0].id, f.clanId), loadClanStatsPage(member, f.users[1].id, f.clanId)]);
    expect(staffModel?.hof.periods.all.minimumGames).toBe(3);
    expect(staffModel?.hof.periods.all.unqualified.map((row) => row.userId).sort()).toEqual([f.users[1].id, f.users[2].id].sort());
    expect(memberModel?.hof.periods.all.unqualified).toEqual([]);
    expect(memberModel?.intraPeriods.all).toMatchObject({ completed: 10, participants: 2 });
    expect(JSON.stringify(memberModel?.intraPeriods)).not.toContain(f.users[1].id);
    await loginIsolatedBalanceUser(page, f.users[0]);
    await page.goto(f.path.replace(/balance$/, "stats"));
    await expect(page.getByText("3경기 이상 출전", { exact: true })).toBeVisible();
    await page.getByText(/규정 미달 2명/).click();
    await expect(page.getByLabel("규정 미달 멤버")).toContainText("0 / 3경기");
    await page.getByRole("tab", { name: "내전 통계" }).click();
    const summary = page.getByLabel("선택 기간 요약");
    const completed = summary.getByRole("button", { name: /완료 경기/ });
    await expect(completed).toContainText("10경기");
    await completed.click();
    await expect(page.getByRole("searchbox", { name: "경기 참가자 검색" })).toHaveCount(0);
    await page.getByRole("radio", { name: "월별", exact: true }).click();
    await page.getByRole("listbox", { name: "연도", exact: true }).press("End");
    const month = page.getByRole("listbox", { name: "월", exact: true });
    await month.press("Home");
    for (let i = 0; i < 6; i++) await month.press("ArrowDown");
    await expect(month.getByRole("option", { selected: true })).toHaveText("7월");
    await expect(completed).toContainText("1경기");
    await expect(page.getByLabel("맵별 경기 비중")).toContainText("부산");
    await month.hover();
    // A large mouse-wheel impulse must advance one month, not skip to December.
    await page.mouse.wheel(0, 800);
    await expect(month.getByRole("option", { selected: true })).toHaveText("8월");
    await expect(completed).toContainText("9경기");
    await expect(page.getByLabel("맵별 경기 비중")).toContainText("네팔");
    const mapTypes = page.getByRole("radiogroup", { name: "맵 유형", exact: true });
    await mapTypes.getByRole("radio", { name: "플래시포인트", exact: true }).click();
    await expect(page.locator('[data-slot="card"]').filter({ has: mapTypes })).toContainText("선택한 조건의 기록이 없습니다.");
    await mapTypes.getByRole("radio", { name: "전체", exact: true }).click();
    const chart = page.getByRole("img", { name: /완료 경기 그래프/ });
    await chart.hover();
    await expect(page.getByRole("status", { name: "참여 추이 선택 값" })).toBeVisible();
    await chart.focus(); await chart.press("Home"); await chart.press("ArrowRight");
    await expect(page.getByRole("status", { name: "참여 추이 선택 값" })).toContainText("9경기");
    await expect(page.getByRole("listbox", { name: "일자", exact: true })).toHaveCount(0);
    await expect(completed).toContainText("9경기");
    await page.getByRole("tab", { name: "경기 기록" }).click();
    await expect(page.getByRole("searchbox", { name: "경기 참가자 검색" })).toBeVisible();
    await expect(page.getByLabel("경기 기록 주간 달력")).toHaveCount(0);
    await page.setViewportSize({ width: 1217, height: 910 });
    const datePicker = page.getByRole("button", { name: /^경기 기록 날짜 선택,/ });
    await expect(datePicker).toContainText("2025년 8월 2일");
    const detail = page.getByRole("region", { name: "경기 상세", exact: true });
    const daily = page.getByRole("complementary", { name: "선택한 날짜 내전 기록" });
    const detailBox = await detail.boundingBox(), dailyBox = await daily.boundingBox();
    expect(dailyBox!.x).toBeGreaterThan(detailBox!.x + detailBox!.width);
    expect(Math.abs(dailyBox!.y - detailBox!.y)).toBeLessThan(2);
    await datePicker.click();
    const calendar = page.getByRole("dialog", { name: "경기 기록 달력" });
    await expect(calendar).toBeVisible();
    await calendar.getByRole("button", { name: "이전 달", exact: true }).click();
    await calendar.getByRole("button", { name: "2025년 7월 1일 경기 기록 있음", exact: true }).click();
    await expect(calendar).toBeHidden();
    await expect(datePicker).toBeFocused();
    await expect(datePicker).toContainText("2025년 7월 1일");
    await expect(detail).toContainText("부산");
    const table = daily.getByRole("table");
    await expect(table.getByRole("rowheader").first()).toHaveText(f.users[0].nickname);
    await table.getByRole("button", { name: "승률 정렬", exact: true }).click();
    await expect(table.getByRole("columnheader", { name: "승률 정렬" })).toHaveAttribute("aria-sort", "ascending");
    await expect(table.getByRole("rowheader").first()).toHaveText(f.users[1].nickname);
    await table.getByRole("button", { name: "승률 정렬", exact: true }).click();
    await expect(table.getByRole("rowheader").first()).toHaveText(f.users[0].nickname);
    for (const name of ["이름 정렬", "승 정렬", "무 정렬", "패 정렬", "당일 현재 연승·연패 정렬", "당일 최장 연승 정렬", "당일 최장 연패 정렬"]) {
      await table.getByRole("button", { name, exact: true }).click();
      const header = table.getByRole("columnheader", { name, exact: true });
      const firstDirection = await header.getAttribute("aria-sort");
      await table.getByRole("button", { name, exact: true }).click();
      await expect(header).toHaveAttribute("aria-sort", firstDirection === "ascending" ? "descending" : "ascending");
    }
    // Filters preserve the chosen date and do not distort the day's streaks.
    await page.getByRole("combobox", { name: "기록 맵" }).selectOption("네팔");
    await expect(detail).toContainText("선택한 조건에 맞는 경기가 없습니다.");
    await expect(datePicker).toContainText("2025년 7월 1일");
    await expect(table.getByRole("rowheader")).toHaveCount(2);
    await page.getByRole("combobox", { name: "기록 맵" }).selectOption("all");
    await page.getByRole("searchbox", { name: "경기 참가자 검색" }).fill("no-such-player");
    await expect(detail).toContainText("선택한 조건에 맞는 경기가 없습니다.");
    await page.getByRole("searchbox", { name: "경기 참가자 검색" }).fill("");
    await datePicker.click();
    await calendar.getByRole("button", { name: "2025년 7월 1일 경기 기록 있음", exact: true }).press("ArrowRight");
    await expect(calendar.getByRole("button", { name: "2025년 7월 2일", exact: true })).toBeFocused();
    await page.keyboard.press("Enter");
    await expect(detail).toContainText("이 날짜에는 기록된 경기가 없습니다.");
    await expect(daily).toContainText("집계할 내전 결과가 없습니다.");
    await datePicker.click();
    await page.keyboard.press("Escape");
    await expect(calendar).toBeHidden();
    await page.setViewportSize({ width: 390, height: 844 });
    await datePicker.click();
    await calendar.getByRole("button", { name: "2025년 7월 1일 경기 기록 있음", exact: true }).click();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.getByRole("tab", { name: "내전 통계" }).click();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole("radio", { name: "월별", exact: true }).click();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.getByRole("tab", { name: "개인 기록" }).click();
    await page.getByRole("button", { name: f.users[0].nickname + " 개인 기록 열기", exact: true }).click();
    await page.setViewportSize({ width: 1217, height: 910 });
    const banner = page.getByRole("region", { name: "플레이어 배너", exact: true });
    const emblems = banner.getByRole("button", { name: f.users[0].nickname + " 엠블럼 컬렉션 열기", exact: true });
    await emblems.hover();
    const collection = page.getByRole("dialog", { name: "엠블럼 컬렉션", exact: true });
    await expect(collection).toBeVisible();
    await collection.getByRole("radio", { name: "연간", exact: true }).click();
    await expect(collection.getByLabel("수상 엠블럼")).toBeVisible();
    await page.keyboard.press("Escape");
    await expect(collection).toBeHidden();
    await emblems.focus();
    await emblems.press("Enter");
    await expect(collection).toBeVisible();
    await collection.getByRole("button", { name: "엠블럼 컬렉션 닫기" }).click();
    await expect(collection).toBeHidden();
    await expect(emblems).toBeFocused();
    await page.setViewportSize({ width: 390, height: 844 });
    const personalPeriod = page.getByRole("region", { name: "개인 기록 기간", exact: true });
    const appearances = page.locator('[data-slot="card"]').filter({ has: page.getByText("출전 경기", { exact: true }) });
    await expect(appearances).toContainText("10경기");
    await personalPeriod.getByRole("radio", { name: "연도별", exact: true }).click();
    await personalPeriod.getByRole("listbox", { name: "연도", exact: true }).press("End");
    await expect(appearances).toContainText("10경기");
    await personalPeriod.getByRole("radio", { name: "월별", exact: true }).click();
    const personalMonth = personalPeriod.getByRole("listbox", { name: "월", exact: true });
    await personalMonth.press("Home");
    await expect(appearances).toContainText("0경기");
    for (let i = 0; i < 6; i++) await personalMonth.press("ArrowDown");
    await expect(appearances).toContainText("1경기");
    await expect(page.getByLabel("맵별 기록 목록")).toContainText("부산");
    await expect(page.getByLabel("맵별 기록 목록").getByRole("img", { name: /맵별 출전, 총 1경기/ })).toBeVisible();
    await expect(page.getByRole("list", { name: "맵별 출전 비중" })).toContainText("승률 100%");
    await expect(page.getByLabel("맵별 기록 목록")).not.toContainText("네팔");
    await personalMonth.press("ArrowDown");
    await expect(appearances).toContainText("9경기");
    await expect(page.getByLabel("맵별 기록 목록")).not.toContainText("부산");
    const flow = page.locator('[data-slot="card-header"]').filter({ has: page.getByText("최근 흐름", { exact: true }) });
    await expect(flow).toContainText("10연승");
    const role = page.getByRole("radiogroup", { name: "내 역할", exact: true });
    await role.getByRole("radio", { name: "돌격", exact: true }).click();
    await expect(role.getByRole("radio", { name: "돌격", exact: true })).toHaveAttribute("title", "돌격");
    await role.getByRole("radio", { name: "돌격", exact: true }).press("ArrowRight");
    await expect(role.getByRole("radio", { name: "공격", exact: true })).toHaveAttribute("aria-checked", "true");
    await page.getByText("역할 조합표 보기", { exact: true }).click();
    const matrix = page.locator("details").filter({ has: page.getByText("역할 조합표 보기", { exact: true }) });
    await expect(matrix.getByRole("columnheader", { name: "돌격", exact: true })).toBeVisible();
    await expect(matrix.getByRole("rowheader", { name: "지원", exact: true })).toBeVisible();
    await expect(page.getByLabel("승부예측 요약")).toContainText("예측 참여0회");
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.getByRole("tab", { name: "명예의 전당" }).click();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  } finally { await f.cleanup(); }
});
