import { expect, test } from "@playwright/test";
import { createAndEnterBalanceRoom, createIsolatedBalanceFixture, loginIsolatedBalanceUser } from "./isolated-balance-fixture";

test("formation settings illustrate each mode without applying it", async ({ page }) => {
  test.setTimeout(90_000);
  const fixture = await createIsolatedBalanceFixture(1);
  try {
    await loginIsolatedBalanceUser(page, fixture.users[0]);
    await createAndEnterBalanceRoom(page, fixture.path, "편성 미리보기 검증");
    const readSettings = async () => {
      const { data, error } = await fixture.service.from("balance_sessions").select("formation_settings").eq("clan_id", fixture.clanId);
      expect(error).toBeNull();
      return data;
    };
    const before = await readSettings();
    await page.clock.install();
    await page.clock.pauseAt(new Date());
    await page.getByRole("button", { name: "라운드 설정", exact: true }).click();
    const dialog = page.getByRole("dialog", { name: "라운드 설정", exact: true });
    const preview = dialog.getByRole("region", { name: "편성 방식 미리보기", exact: true });
    const mode = dialog.getByRole("combobox", { name: "팀원 선발 방식", exact: true });
    const caption = preview.getByTestId("formation-preview-caption");
    const title = preview.getByTestId("formation-preview-title");
    const progress = preview.getByTestId("formation-preview-step");
    const advance = async (steps = 1) => page.clock.runFor(2400 * steps);
    const cycleLength = async () => Number((await progress.innerText()).split("/")[1].trim());
    await expect(preview).toBeVisible();
    const panel = page.getByTestId("balance-settings-panel");
    const previewBox = await preview.boundingBox();
    const panelBox = await panel.boundingBox();
    expect(previewBox!.x + previewBox!.width).toBeLessThan(panelBox!.x);
    expect(previewBox!.width).toBeGreaterThan(450);
    await expect(caption).toContainText("그대로 사용");
    await expect(dialog.getByRole("radio", { name: /수동 배정/ })).toBeChecked();
    await expect(dialog.getByRole("radio", { name: /자동 배정/ })).toBeVisible();
    await mode.selectOption("random");
    await advance(3);
    await expect(title).toHaveText("돌격 팀 추첨");
    await expect(preview.locator('[data-preview-team="A"]')).toHaveCount(1);
    await expect(preview.locator('[data-preview-team="B"]')).toHaveCount(1);
    await preview.getByRole("button", { name: "미리보기 일시정지", exact: true }).click();
    await page.clock.runFor(5000);
    await expect(title).toHaveText("돌격 팀 추첨");
    await preview.getByRole("button", { name: "미리보기 재생", exact: true }).click();
    await advance();
    await expect(title).toHaveText("첫 공격 자리 추첨");
    await preview.getByRole("button", { name: "미리보기 다시 보기", exact: true }).click();
    await expect(title).toHaveText("수동 명단 확인");
    await advance(await cycleLength() - 1);
    await expect(title).toHaveText("팀 구성 완료");
    await expect(preview.locator('[data-preview-team="A"]')).toHaveCount(5);
    await expect(preview.locator('[data-preview-team="B"]')).toHaveCount(5);
    await preview.getByRole("button", { name: "미리보기 일시정지", exact: true }).click();
    await advance(2);
    await expect(title).toHaveText("팀 구성 완료");
    await preview.getByRole("button", { name: "미리보기 재생", exact: true }).click();
    await advance();
    await expect(title).toHaveText("수동 명단 확인");
    await advance(await cycleLength());
    await expect(title).toHaveText("수동 명단 확인");

    await dialog.getByRole("radio", { name: /자동 배정/ }).check();
    const screen = preview.getByTestId("auto-draw-screen");
    await expect(title).toHaveText("내 선호 역할 선택");
    await expect(screen).toHaveAttribute("data-screen", "preference");
    const autoBox = await preview.boundingBox();
    expect(autoBox!.y).toBeGreaterThanOrEqual(0);
    expect(autoBox!.y + autoBox!.height).toBeLessThanOrEqual(page.viewportSize()!.height);
    await page.screenshot({ animations: "disabled", path: test.info().outputPath("auto-preference-preview.png") });
    await advance();
    await expect(title).toHaveText("지원 1순위로 변경");
    await expect(screen.locator("[data-preview-preference]").first()).toHaveAttribute("data-preview-preference", "sup");
    await advance();
    await expect(screen).toHaveAttribute("data-screen", "roster");
    await expect(preview.getByRole("group", { name: "내 선호 역할 선택 화면" })).toHaveCount(0);
    await expect(screen).toContainText("역할 배정 전");
    await advance();
    await expect(screen).toHaveAttribute("data-screen", "draw");
    await expect(screen.locator('[data-revealed="true"]')).toHaveCount(0);
    const rolling = await screen.locator('[data-preview-player="0"] strong').innerText();
    await page.clock.runFor(400);
    expect(await screen.locator('[data-preview-player="0"] strong').innerText()).not.toEqual(rolling);
    await page.clock.runFor(600);
    await expect(title).toHaveText("1번째 발표 · 모찌");
    await expect(screen.locator('[data-revealed="true"]')).toHaveCount(1);
    await page.clock.runFor(2400);
    await expect(title).toHaveText("4번째 발표 · 여우");
    await expect(screen.locator('[data-preview-player="8"]')).toHaveAttribute("data-preview-team", "B");
    await expect(screen.locator('[data-preview-player="8"]')).toContainText("지원");
    await preview.getByRole("button", { name: "미리보기 일시정지", exact: true }).click();
    const pausedNames = await screen.locator('[data-revealed="false"] strong').allTextContents();
    await page.clock.runFor(2400);
    expect(await screen.locator('[data-revealed="false"] strong').allTextContents()).toEqual(pausedNames);
    await page.screenshot({ animations: "disabled", path: test.info().outputPath("auto-draw-preview.png") });
    expect((await preview.boundingBox())!.height).toBe(autoBox!.height);
    await preview.getByRole("button", { name: "미리보기 재생", exact: true }).click();
    await page.clock.runFor(5600);
    await expect(title).toHaveText("팀 구성 완료");
    await expect(screen).toHaveAttribute("data-screen", "complete");
    await expect(screen.locator('[data-preview-team="A"]')).toHaveCount(5);
    await expect(screen.locator('[data-preview-team="B"]')).toHaveCount(5);
    await page.clock.runFor(3200);
    await expect(screen).toHaveAttribute("data-screen", "preference");
    await dialog.getByRole("radio", { name: /수동 배정/ }).check();

    await mode.selectOption("draft");
    await advance(4);
    await expect(title).toHaveText("1번째 지명 · A팀");
    await expect(preview.locator('[data-preview-player="2"]')).toHaveAttribute("data-preview-team", "A");
    await advance();
    await expect(title).toHaveText("2번째 지명 · B팀");
    await advance();
    await expect(title).toHaveText("3번째 지명 · B팀");
    await expect(preview.locator('[data-preview-player="4"]')).toHaveAttribute("data-preview-team", "B");

    await mode.selectOption("auction");
    await dialog.getByRole("spinbutton", { name: "최소·증액 단위", exact: true }).fill("20");
    await expect(title).toHaveText("A팀 주장 시점");
    await advance(3);
    const timer = preview.getByTestId("auction-preview-timer");
    const price = preview.getByTestId("auction-preview-price");
    await expect(timer).toHaveText("20초");
    const auctionBox = await preview.boundingBox();
    expect(auctionBox!.y).toBeGreaterThanOrEqual(0);
    expect(auctionBox!.y + auctionBox!.height).toBeLessThanOrEqual(page.viewportSize()!.height);
    await page.clock.runFor(1000);
    await expect(timer).toHaveText("19초");
    await preview.getByRole("button", { name: "미리보기 일시정지", exact: true }).click();
    await page.clock.runFor(5000);
    await expect(timer).toHaveText("19초");
    await preview.getByRole("button", { name: "미리보기 재생", exact: true }).click();
    await page.clock.runFor(1000);
    await expect(title).toHaveText("내 첫 입찰");
    await expect(price).toHaveText("20 cr");
    await page.clock.runFor(2000);
    await expect(title).toHaveText("상대 팀 입찰 도착");
    await expect(price).toHaveText("40 cr");
    await expect(timer).toHaveText("16초");
    await page.clock.runFor(13000);
    await expect(title).toHaveText("내 재입찰 · 시간 연장");
    await expect(timer).toHaveText("5초");
    await expect(price).toHaveText("60 cr");
    await expect(preview.getByTestId("auction-preview-notice")).toContainText("3초 → 5초");
    expect((await preview.boundingBox())!.height).toBe(auctionBox!.height);
    await page.screenshot({ animations: "disabled", path: test.info().outputPath("auction-preview.png") });
    await page.clock.runFor(5000);
    await expect(title).toHaveText("입찰 마감");
    await expect(timer).toHaveText("0초");
    await advance();
    await expect(title).toHaveText("선수 합류 · 크레딧 차감");
    await expect(preview.getByTestId("preview-credits-0")).toHaveText("940 cr");
    await expect(preview.locator('[data-preview-player="2"]')).toHaveAttribute("data-preview-team", "A");
    await dialog.getByRole("tab", { name: "화면 표시", exact: true }).click();
    await page.clock.runFor(300);
    await expect(preview).toBeHidden();
    await dialog.getByRole("tab", { name: "편성", exact: true }).click();
    await page.emulateMedia({ reducedMotion: "reduce" });
    await expect(title).toHaveText("팀 구성 완료");
    await expect(preview.getByTestId("preview-credits-0")).toHaveText("880 cr");
    await expect(preview.getByTestId("preview-credits-1")).toHaveText("900 cr");
    await expect(preview.getByRole("button")).toHaveCount(0);
    await mode.selectOption("random");
    await expect(caption).toContainText("각 팀에 돌격 1");
    await page.setViewportSize({ width: 390, height: 844 });
    await preview.scrollIntoViewIfNeeded();
    expect(await preview.evaluate((el) => el.scrollWidth <= el.clientWidth)).toBe(true);
    const mobilePreview = await preview.boundingBox();
    const mobilePanel = await panel.boundingBox();
    expect(mobilePreview!.x).toBeGreaterThanOrEqual(mobilePanel!.x);
    expect(mobilePreview!.x + mobilePreview!.width).toBeLessThanOrEqual(mobilePanel!.x + mobilePanel!.width);
    await dialog.getByRole("radio", { name: /자동 배정/ }).check();
    await expect(screen).toHaveAttribute("data-screen", "complete");
    await expect(screen.locator('[data-revealed="true"]')).toHaveCount(10);
    await expect(preview.getByRole("button")).toHaveCount(0);
    await page.emulateMedia({ reducedMotion: "no-preference" });
    await expect(screen).toHaveAttribute("data-screen", "preference");
    await preview.scrollIntoViewIfNeeded();
    expect(await screen.evaluate((el) => el.scrollWidth <= el.clientWidth)).toBe(true);
    await advance(3);
    await page.clock.runFor(9000);
    await expect(screen).toHaveAttribute("data-screen", "complete");
    await preview.scrollIntoViewIfNeeded();
    expect(await screen.locator('[data-preview-player="8"]').evaluate((el) => el.getBoundingClientRect().bottom <= el.closest('[data-testid="auto-draw-screen"]')!.getBoundingClientRect().bottom)).toBe(true);
    await page.screenshot({ animations: "disabled", path: test.info().outputPath("auto-mobile-preview.png") });
    expect(await readSettings()).toEqual(before);
    await page.keyboard.press("Escape");
    await page.clock.runFor(300);
    await expect(dialog).toBeHidden();
  } finally {
    await fixture.cleanup();
  }
});
