import { expect, test } from "@playwright/test";
import { createAndEnterBalanceRoom, createIsolatedBalanceFixture, loginIsolatedBalanceUser } from "./isolated-balance-fixture";

test("화면 표시·밴픽 미리보기와 종속 설정은 초안만 반영하고 적용 시 저장", async ({ page }) => {
  test.setTimeout(90_000);
  const fixture = await createIsolatedBalanceFixture(1);
  try {
    await loginIsolatedBalanceUser(page, fixture.users[0]);
    const { roomId } = await createAndEnterBalanceRoom(page, fixture.path, "화면과 밴픽 미리보기 검증");
    const round = await fixture.activeRound(roomId);
    expect((await fixture.service.from("balance_sessions").update({ map_ban_enabled: false, hero_ban_enabled: false }).eq("id", round.id)).error).toBeNull();
    await page.reload();
    const picker = page.getByRole("dialog", { name: "경기 맵 선택", exact: true });
    await picker.getByRole("button", { name: "부산 선택", exact: true }).click();
    await expect(picker).toBeHidden();
    const before = await fixture.activeRound(roomId);
    await page.getByRole("button", { name: "경기 설정", exact: true }).click();
    const dialog = page.getByRole("dialog", { name: "경기 설정", exact: true });
    const options = dialog.getByTestId("balance-settings-panel");
    await dialog.getByRole("tab", { name: "화면 표시", exact: true }).click();
    const display = dialog.getByRole("region", { name: "화면 표시 미리보기", exact: true });
    const card = display.getByTestId("display-preview-card-0");
    await expect(display).toBeVisible();
    await expect(dialog.getByRole("region", { name: "편성 방식 미리보기", exact: true })).toBeHidden();
    await expect(options.getByRole("group", { name: "닉네임 카드", exact: true }).getByRole("checkbox")).toHaveCount(3);
    await expect(options.getByRole("group", { name: "팀 비교", exact: true }).getByRole("checkbox")).toHaveCount(1);
    await expect(card).toContainText("+1.2");
    const scoreGraph = display.getByTestId("team-comparison-graph");
    const titleBox = await scoreGraph.getByText("평가 점수 합계", { exact: true }).boundingBox();
    const firstScore = await scoreGraph.getByTestId("team1-score-total").boundingBox();
    const secondScore = await scoreGraph.getByTestId("team2-score-total").boundingBox();
    expect(Math.abs(titleBox!.y + titleBox!.height / 2 - firstScore!.y - firstScore!.height / 2)).toBeLessThan(2);
    expect(titleBox!.x).toBeGreaterThanOrEqual(firstScore!.x + firstScore!.width);
    expect(titleBox!.x + titleBox!.width).toBeLessThanOrEqual(secondScore!.x);
    await options.getByRole("checkbox", { name: "선수 카드 점수 표시", exact: true }).uncheck();
    await expect(card).not.toContainText("+1.2");
    await options.getByRole("checkbox", { name: "선수 카드 점수 표시", exact: true }).check();
    await display.getByRole("button", { name: "분석 점수", exact: true }).click();
    await expect(card).toContainText("+2.1");
    await options.getByRole("combobox", { name: "선수 카드 보조 정보", exact: true }).selectOption("streak");
    await expect(card).toContainText("2연승");
    await options.getByRole("checkbox", { name: "선수 카드 보조 정보 표시", exact: true }).uncheck();
    await expect(card).not.toContainText("2연승");
    await expect(options.getByRole("combobox", { name: "선수 카드 보조 정보", exact: true })).toHaveCount(0);
    await options.getByRole("checkbox", { name: "선수 카드 보조 정보 표시", exact: true }).check();
    await expect(options.getByRole("combobox", { name: "선수 카드 보조 정보", exact: true })).toHaveValue("streak");
    await options.getByRole("combobox", { name: "팀 비교 그래프", exact: true }).selectOption("prediction");
    await expect(display.getByTestId("team-comparison-graph")).toHaveAttribute("data-mode", "prediction");
    await card.hover();
    await expect(page.getByRole("tooltip").filter({ hasText: "이번 세션 전적" })).toBeVisible();
    await options.getByRole("checkbox", { name: "플레이어 세션 정보 요약 표시", exact: true }).uncheck();
    await card.hover();
    await expect(page.getByRole("tooltip").filter({ hasText: "이번 세션 전적" })).toHaveCount(0);
    await page.screenshot({ path: test.info().outputPath("display-settings-preview-desktop.png") });
    await dialog.getByRole("tab", { name: "경기 구성", exact: true }).click();
    const bans = dialog.getByTestId("balance-ban-preview");
    await expect(display).toBeHidden();
    await expect(bans).toHaveAttribute("data-stage", "match");
    await expect(options.getByRole("spinbutton")).toHaveCount(0);
    await expect(options.getByRole("combobox", { name: "팀별 영웅 밴 개수", exact: true })).toHaveCount(0);
    await expect(bans.getByRole("navigation", { name: "밴픽 진행 순서", exact: true }).getByRole("button")).toHaveCount(1);
    await options.getByRole("checkbox", { name: "맵 투표 사용", exact: true }).check();
    await options.getByRole("spinbutton", { name: "맵 투표 시간(초)", exact: true }).fill("45");
    expect(await options.getByRole("spinbutton", { name: "맵 투표 시간(초)", exact: true }).evaluate((input) => getComputedStyle(input).appearance)).toBe("textfield");
    await expect(bans.getByTestId("ban-preview-map-time")).toHaveText("45초");
    await bans.getByRole("button", { name: "오아시스 미리보기 투표", exact: true }).click();
    await expect(bans.getByRole("button", { name: "오아시스 미리보기 투표", exact: true })).toHaveAttribute("aria-pressed", "true");
    await options.getByRole("checkbox", { name: "영웅 밴 사용", exact: true }).check();
    await expect(bans).toHaveAttribute("data-stage", "hero");
    await options.getByRole("combobox", { name: "팀별 영웅 밴 개수", exact: true }).selectOption("1");
    await expect(bans).toContainText("팀당 최대 1명");
    await options.getByRole("spinbutton", { name: "영웅 밴 시간(초)", exact: true }).fill("35");
    await expect(bans.getByTestId("ban-preview-hero-time")).toHaveText("35초");
    await bans.getByRole("button", { name: "아나 미리보기 밴", exact: true }).click();
    await expect(bans.getByRole("button", { name: "아나 미리보기 밴", exact: true })).toHaveAttribute("aria-pressed", "true");
    await expect(bans.getByRole("button", { name: "트레이서 미리보기 밴", exact: true })).toHaveAttribute("aria-pressed", "false");
    await options.getByRole("checkbox", { name: "영웅 밴 사용", exact: true }).uncheck();
    await expect(options.getByRole("spinbutton", { name: "영웅 밴 시간(초)", exact: true })).toHaveCount(0);
    await options.getByRole("checkbox", { name: "영웅 밴 사용", exact: true }).check();
    await expect(options.getByRole("spinbutton", { name: "영웅 밴 시간(초)", exact: true })).toHaveValue("35");
    expect((await fixture.activeRound(roomId)).formation_settings).toEqual(before.formation_settings);
    expect((await fixture.activeRound(roomId)).map_ban_enabled).toBe(false);
    expect((await fixture.activeRound(roomId)).resolved_map_label).toBe("부산");
    await page.screenshot({ path: test.info().outputPath("ban-settings-preview-desktop.png") });
    await page.setViewportSize({ width: 390, height: 844 });
    await bans.scrollIntoViewIfNeeded();
    expect(await bans.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
    await page.screenshot({ path: test.info().outputPath("ban-settings-preview-mobile.png") });
    await dialog.getByRole("tab", { name: "화면 표시", exact: true }).click();
    for (const width of [320, 390]) {
      await page.setViewportSize({ width, height: 844 });
      await display.scrollIntoViewIfNeeded();
      expect(await display.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true);
      const heading = display.getByTestId("display-preview-team-heading");
      const team1 = await heading.getByText("1팀", { exact: true }).boundingBox();
      const graph = await heading.getByTestId("team-comparison-graph").boundingBox();
      const team2 = await heading.getByText("2팀", { exact: true }).boundingBox();
      expect(team1!.x + team1!.width).toBeLessThanOrEqual(graph!.x);
      expect(graph!.x + graph!.width).toBeLessThanOrEqual(team2!.x);
    }
    await page.screenshot({ path: test.info().outputPath("display-settings-preview-mobile.png") });
    await options.getByRole("button", { name: "설정 적용", exact: true }).click();
    await expect(dialog).toBeHidden();
    await expect.poll(async () => (await fixture.activeRound(roomId)).formation_settings).toMatchObject({ playerCardInfo: "streak", teamComparisonMode: "prediction", showPlayerSessionSummary: false });
    const saved = await fixture.activeRound(roomId);
    expect(saved).toMatchObject({ map_ban_enabled: true, hero_ban_enabled: true, map_ban_seconds: 45, hero_ban_seconds: 35, hero_bans_per_team: 1 });
    await page.reload();
    await page.getByRole("button", { name: "경기 설정", exact: true }).click();
    await dialog.getByRole("tab", { name: "경기 구성", exact: true }).click();
    await expect(options.getByRole("spinbutton", { name: "맵 투표 시간(초)", exact: true })).toHaveValue("45");
    await expect(options.getByRole("combobox", { name: "팀별 영웅 밴 개수", exact: true })).toHaveValue("1");
  } finally { await fixture.cleanup(); }
});

test("formation previews support readable pacing, seeking and every screen flow without saving", async ({ page }) => {
  test.setTimeout(90_000);
  const fixture = await createIsolatedBalanceFixture(1);
  try {
    await loginIsolatedBalanceUser(page, fixture.users[0]);
    await createAndEnterBalanceRoom(page, fixture.path, "편성 미리보기 검증");
    const readSettings = async () => {
      const { data, error } = await fixture.service.from("balance_sessions").select("formation_settings").eq("clan_id", fixture.clanId);
      expect(error).toBeNull();
      return data;
    };
    const before = await readSettings();
    await page.clock.install();
    await page.clock.pauseAt(new Date());
    await page.getByRole("button", { name: "경기 설정", exact: true }).click();
    const dialog = page.getByRole("dialog", { name: "경기 설정", exact: true });
    const preview = dialog.getByRole("region", { name: "편성 방식 미리보기", exact: true });
    const mode = dialog.getByRole("combobox", { name: "팀원 선발 방식", exact: true });
    const screen = preview.getByTestId("formation-preview-screen");
    const title = preview.getByTestId("formation-preview-title");
    const timeline = preview.getByRole("slider", { name: "미리보기 타임라인" });
    const seek = async (step: number) => timeline.fill(String(step));
    const chapter = async (name: string) => preview.getByRole("button", { name: new RegExp(`${name}(?: \\d+)? 구간 보기$`) }).first().click();
    const play = async () => preview.getByRole("button", { name: "미리보기 재생", exact: true }).click();
    const expectTeams = async () => {
      await expect(screen.locator('[data-preview-team="A"]')).toHaveCount(5);
      await expect(screen.locator('[data-preview-team="B"]')).toHaveCount(5);
    };
    const panel = page.getByTestId("balance-settings-panel");
    const previewBox = await preview.boundingBox();
    const panelBox = await panel.boundingBox();
    const normalScreenHeight = (await screen.boundingBox())!.height;
    expect(previewBox!.x + previewBox!.width).toBeLessThan(panelBox!.x);
    expect(previewBox!.y).toBeGreaterThanOrEqual(0);
    expect(previewBox!.y + previewBox!.height).toBeLessThanOrEqual(page.viewportSize()!.height);

    await expect(screen).toHaveAttribute("data-screen", "manual");
    await page.clock.runFor(3800);
    await expect(title).toHaveText("수동 명단 확인");
    await page.clock.runFor(200);
    await expect(title).toHaveText("역할 인원 확인");
    await seek(0);
    await page.clock.runFor(12000);
    await expect(title).toHaveText("수동 명단 확인");
    await timeline.focus();
    await page.keyboard.press("ArrowRight");
    await expect(title).toHaveText("역할 인원 확인");
    await chapter("결과");
    await expectTeams();
    await play();
    await page.clock.runFor(4000);
    await expect(title).toHaveText("수동 명단 확인");

    await mode.selectOption("random");
    await chapter("추첨 발표");
    await expect(screen).toHaveAttribute("data-screen", "draw");
    await expect(screen.locator('[data-revealed="true"]')).toHaveCount(0);
    await seek(3);
    await expect(title).toHaveText("돌격 팀 추첨");
    await expect(screen.locator('[data-revealed="true"]')).toHaveCount(2);
    await chapter("결과");
    await expectTeams();

    await dialog.getByRole("radio", { name: /자동 배정/ }).check();
    await expect(screen).toHaveAttribute("data-screen", "preference");
    await page.clock.runFor(3800);
    await expect(title).toHaveText("내 선호 역할 선택");
    await seek(1);
    await expect(screen.locator("[data-preview-preference]").first()).toHaveAttribute("data-preview-preference", "sup");
    await chapter("명단 확인");
    await expect(screen).toHaveAttribute("data-screen", "roster");
    await expect(preview.getByRole("group", { name: "내 선호 역할 선택 화면", exact: true })).toHaveCount(0);
    await chapter("추첨 발표");
    const frozenNames = await screen.locator('[data-revealed="false"] strong').allTextContents();
    await page.clock.runFor(2000);
    expect(await screen.locator('[data-revealed="false"] strong').allTextContents()).toEqual(frozenNames);
    await play();
    await page.clock.runFor(200);
    expect(await screen.locator('[data-revealed="false"] strong').allTextContents()).not.toEqual(frozenNames);
    await page.clock.runFor(200);
    await expect(title).toHaveText("추첨 발표");
    await expect(screen.locator('[data-revealed="true"]')).toHaveCount(1);
    await expect(preview.getByTestId("formation-preview-step")).toHaveText("4 / 5");
    await page.clock.runFor(1000);
    await expect(screen.locator('[data-preview-player="8"]')).toHaveAttribute("data-preview-team", "B");
    await expect(screen.locator('[data-preview-player="8"]')).toContainText("지원");
    await preview.getByRole("button", { name: "미리보기 일시정지", exact: true }).click();
    await page.clock.runFor(2000);
    await expect(screen.locator('[data-revealed="true"]')).toHaveCount(4);
    await expect(preview.getByTestId("formation-preview-step")).toHaveText("4 / 5");
    await page.screenshot({ animations: "disabled", path: test.info().outputPath("auto-timeline-preview.png") });
    await play();
    await page.clock.runFor(1600);
    await expect(screen.locator('[data-revealed="true"]')).toHaveCount(10);
    await expect(title).toHaveText("추첨 발표");
    await expect(preview.getByTestId("formation-preview-step")).toHaveText("4 / 5");
    await page.clock.runFor(1000);
    await expect(screen).toHaveAttribute("data-screen", "complete");
    await expectTeams();
    await page.clock.runFor(4000);
    await expect(screen).toHaveAttribute("data-screen", "preference");

    for (const teamMode of ["draft", "auction"]) {
      await mode.selectOption(teamMode);
      await expect(screen).toHaveAttribute("data-screen", "preference");
      await chapter("추첨 발표");
      await play();
      await page.clock.runFor(1400);
      await expect(screen.locator('[data-revealed="true"]')).toHaveCount(4);
      await expect(screen).toContainText("역할 자리");
      await chapter("결과");
      await expectTeams();
    }
    await dialog.getByRole("radio", { name: /수동 배정/ }).check();
    await mode.selectOption("draft");
    await chapter("주장 선정");
    await expect(screen).toHaveAttribute("data-screen", "captains");
    await chapter("지명");
    await expect(screen).toHaveAttribute("data-screen", "draft");
    await seek(4);
    await expect(title).toHaveText("1번째 지명 · A팀");
    await seek(6);
    await expect(title).toHaveText("3번째 지명 · B팀");
    await page.screenshot({ animations: "disabled", path: test.info().outputPath("draft-timeline-preview.png") });
    await chapter("결과");
    await expectTeams();

    await mode.selectOption("auction");
    const extensionBox = await dialog.getByLabel("입찰 연장 시간(초)", { exact: true }).boundingBox();
    const preparationBox = await dialog.getByLabel("낙찰 후 준비 시간(초)", { exact: true }).boundingBox();
    expect(extensionBox!.y < preparationBox!.y || (extensionBox!.y === preparationBox!.y && extensionBox!.x < preparationBox!.x)).toBe(true);
    await dialog.getByRole("spinbutton", { name: "최소·증액 단위", exact: true }).fill("20");
    await chapter("입찰");
    await expect(screen).toHaveAttribute("data-screen", "auction");
    await expect(title).toHaveText("A팀 주장 시점");
    await seek(4);
    const timer = preview.getByTestId("auction-preview-timer");
    const price = preview.getByTestId("auction-preview-price");
    await expect(timer).toHaveText("20초");
    await play();
    await page.clock.runFor(2000);
    await expect(timer).toHaveText("19초");
    await page.clock.runFor(2000);
    await expect(title).toHaveText("내 첫 입찰");
    await expect(price).toHaveText("20 cr");
    await seek(6);
    await expect(price).toHaveText("40 cr");
    await play();
    await page.clock.runFor(4000);
    await expect(title).toHaveText("내 재입찰 · 시간 연장");
    await expect(timer).toHaveText("5초");
    await expect(price).toHaveText("60 cr");
    await page.screenshot({ animations: "disabled", path: test.info().outputPath("auction-timeline-preview.png") });
    await page.clock.runFor(4000);
    await expect(screen).toHaveAttribute("data-screen", "settlement");
    await expect(timer).toHaveText("0초");
    await page.clock.runFor(4000);
    await expect(preview.getByTestId("preview-credits-0")).toHaveText("940 cr");
    await expect(preview.getByTestId("auction-preview-preparation")).toHaveText("5초");
    await expect(preview.getByRole("button", { name: /입찰.*구간 보기/ })).toHaveCount(1);
    await expect(preview.getByRole("button", { name: /낙찰.*구간 보기/ })).toHaveCount(1);
    await dialog.getByLabel("낙찰 후 준비 시간(초)", { exact: true }).fill("12");
    await seek(9);
    await expect(preview.getByTestId("auction-preview-preparation")).toHaveText("12초");
    await dialog.getByLabel("입찰 연장 시간(초)", { exact: true }).fill("8");
    await seek(7);
    await expect(timer).toHaveText("8초");
    await expect(preview.getByTestId("formation-preview-caption")).toContainText("마지막 8초");
    await chapter("결과");
    await expectTeams();
    await expect(preview.getByTestId("preview-credits-0")).toHaveText("880 cr");
    await expect(preview.getByTestId("preview-credits-1")).toHaveText("900 cr");
    await dialog.getByRole("checkbox", { name: "전략 아이템 사용" }).check();
    await chapter("전략 준비");
    await expect(screen).toHaveAttribute("data-screen", "strategy");
    await chapter("아이템 선택");
    await expect(screen).toHaveAttribute("data-screen", "items");
    await expect(screen).toContainText("구매 안 함");
    await expect(screen).toContainText("영웅 밴 1장");
    await expect(screen).toContainText("맵 선택권 1장");
    await expect(screen).toContainText("영웅 밴 2장");
    await expect(screen).toContainText("100cr");
    await expect(screen).toContainText("50cr");
    await expect(screen).toContainText("200cr");

    for (const setting of [
      { label: "팀 크레딧", field: "auctionBudget", value: "1500", restore: "1000", scene: "auction", text: "1000 cr → 1500 cr" },
      { label: "최소·증액 단위", field: "minBid", value: "40", restore: "20", scene: "auction", text: "10 cr → 40 cr" },
      { label: "입찰 시간(초)", field: "durationSeconds", value: "35", restore: "20", scene: "auction", text: "20초 → 35초" },
      { label: "낙찰 후 준비 시간(초)", field: "auctionPreparationSeconds", value: "15", restore: "12", scene: "preparation", text: "5초 → 15초" },
      { label: "입찰 연장 시간(초)", field: "bidExtensionSeconds", value: "0", restore: "8", scene: "auction", text: "5초 → 0초 (연장 끔)" },
      { label: "전략 준비 시간(초)", field: "strategySeconds", value: "45", restore: "30", scene: "strategy", text: "30초 → 45초" },
    ]) {
      const input = dialog.getByRole("spinbutton", { name: setting.label, exact: true });
      await input.focus();
      await expect(screen.locator(`[data-preview-highlight="${setting.field}"]`)).toBeVisible();
      await input.fill(setting.value);
      await expect(screen).toHaveAttribute("data-screen", setting.scene);
      await expect(screen.getByRole("status")).toContainText(setting.text);
      await expect(screen.getByRole("status")).toHaveClass("sr-only");
      await expect(screen.locator("[data-preview-highlight]")).toHaveCount(1);
      const highlight = await screen.locator(`[data-preview-highlight="${setting.field}"]`).boundingBox();
      const unchangedScreen = await screen.boundingBox();
      expect(unchangedScreen!.height).toBe(normalScreenHeight);
      if (setting.field === "auctionBudget") {
        expect(highlight!.height).toBeLessThan(40);
        expect(highlight!.width).toBeLessThan(unchangedScreen!.width / 2);
      }
      const pausedTitle = await title.textContent();
      await page.clock.runFor(12000);
      await expect(title).toHaveText(pausedTitle!);
      await input.fill(setting.restore);
    }
    await play();
    await expect(screen.locator("[data-preview-highlight]")).toHaveCount(0);
    await chapter("입찰");
    await dialog.getByRole("spinbutton", { name: "입찰 연장 시간(초)", exact: true }).fill("8");
    await expect(preview.getByTestId("auction-preview-timer")).toHaveText("8초");
    await page.screenshot({ animations: "disabled", path: test.info().outputPath("setting-highlight-preview.png") });

    await page.emulateMedia({ reducedMotion: "reduce" });
    await mode.selectOption("random");
    await expect(screen).toHaveAttribute("data-screen", "complete");
    await chapter("역할 배치");
    await expect(screen).toHaveAttribute("data-screen", "manual");
    await page.clock.runFor(12000);
    await expect(screen).toHaveAttribute("data-screen", "manual");
    await page.setViewportSize({ width: 390, height: 844 });
    await dialog.getByRole("radio", { name: /자동 배정/ }).check();
    await chapter("추첨 발표");
    await expect(screen.locator('[data-revealed="true"]')).toHaveCount(10);
    await chapter("선호 선택");
    await preview.scrollIntoViewIfNeeded();
    expect(await screen.evaluate((el) => el.scrollWidth <= el.clientWidth)).toBe(true);
    await chapter("결과");
    await expectTeams();
    await preview.scrollIntoViewIfNeeded();
    expect(await screen.locator('[data-preview-player="8"]').evaluate((el) => el.getBoundingClientRect().bottom <= el.closest('[data-testid="formation-preview-screen"]')!.getBoundingClientRect().bottom)).toBe(true);
    await mode.selectOption("auction");
    await dialog.getByRole("spinbutton", { name: "입찰 시간(초)", exact: true }).fill("40");
    await expect(screen.getByRole("status")).toContainText("20초 → 40초");
    await expect(preview.getByTestId("auction-preview-timer")).toHaveText("40초");
    await preview.scrollIntoViewIfNeeded();
    const highlightedBox = await screen.locator('[data-preview-highlight="durationSeconds"]').boundingBox();
    const screenBox = await screen.boundingBox();
    expect(highlightedBox!.y + highlightedBox!.height).toBeLessThanOrEqual(screenBox!.y + screenBox!.height);
    await chapter("입찰");
    await seek(Number(await timeline.inputValue()) + 1);
    await preview.scrollIntoViewIfNeeded();
    expect(await screen.evaluate((el) => el.scrollWidth <= el.clientWidth)).toBe(true);
    expect(await screen.getByTestId("auction-preview-timer").evaluate((el) => el.getBoundingClientRect().bottom <= el.closest('[data-testid="formation-preview-screen"]')!.getBoundingClientRect().bottom)).toBe(true);
    await chapter("아이템 선택");
    await page.screenshot({ animations: "disabled", path: test.info().outputPath("mobile-timeline-preview.png") });
    await mode.selectOption("draft");
    await chapter("지명");
    const draftStatus = screen.getByText("0 / 8명 선발 · 역할 정원 안에서 선택해요.", { exact: true });
    expect(await draftStatus.evaluate((el) => el.getBoundingClientRect().bottom <= el.closest('[data-testid="formation-preview-screen"]')!.getBoundingClientRect().bottom)).toBe(true);
    await dialog.getByRole("tab", { name: "화면 표시", exact: true }).click();
    await page.clock.runFor(300);
    await expect(preview).toBeHidden();
    await expect(await readSettings()).toEqual(before);
    await page.keyboard.press("Escape");
    await page.clock.runFor(300);
    await expect(dialog).toBeHidden();
  } finally {
    await fixture.cleanup();
  }
});
